# Copyright 2023, Dustin Keate, All rights reserved.

# Even Fibonacci Numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
# starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.



fib_previous = 1
fib_current = 1
fib_next = 0

result = 0

while(fib_current < 4000000):
  fib_next = fib_previous + fib_current

  print(fib_current)
  
  if fib_current%2 == 0:
    result += fib_current

  fib_next = fib_previous + fib_current
  fib_previous = fib_current
  fib_current = fib_next

print(result)
